### ISSUE TITLE
多租户基本原则

### ISSUE THREAD

**Issue by Guo-Zhang** [quanttide/quanttide-specification-of-multitenants#2]
主要以django-tenants库的实现为参考。

数据库采取表隔离策略。对于MySQL，计划使用tenant_app_model的格式，通过命名隔离租户，以模拟PGSQL的用schema定义租户的策略。

API可以使用子域名，也可以使用tenants/name的路径隔离，或者也可以考虑使用请求头隔离。方案2对于跨租户访问资源最友好，方案3也可以。

**Comment by Guo-Zhang** [comment]
https://django-tenants.readthedocs.io/en/latest/#:~:text=Welcome%20to%20django-tenants%20documentation%21%20%C2%B6%20This%20application%20enables,instance%2C%20even%20when%20only%20the%20data%20is%20different.

**Comment by huangrihang** [comment]
方案2可以

**Comment by Guo-Zhang** [comment]
数据库隔离有三种方案：
1. 租户ID隔离。缺点是租户内部的unique约束等不好搞，且资源隔离不够充分。
2. 表隔离。比较理想的平衡。Django可以通过Migration机制来复制表结构。
3. 库隔离。对Django来说不好处理，比如需要建库的权限，还需要写Router。SQL也不好做跨库的计算。

**Comment by huangrihang** [comment]
数据库隔离方案2（表隔离）可以

**Comment by Guo-Zhang** [comment]
参考资料：https://learn.microsoft.com/en-us/azure/azure-sql/database/saas-tenancy-app-design-patterns?view=azuresql
